package model

import (
	"cryingbear.net/go-mtgjson-api/util"
	"github.com/google/uuid"
)

type CardAtomic struct {
	AsciiName               *string           `json:"asciiName,omitempty"`
	ColorIdentity           []string          `json:"colorIdentity"`
	ColorIndicator          *[]string         `json:"colorIndicator,omitempty"`
	Colors                  []string          `json:"colors"`
	ConvertedManaCost       float64           `json:"convertedManaCost"`
	Defense                 *string           `json:"defense,omitempty"`
	EdhrecRank              *int              `json:"edhrecRank,omitempty"`
	EdhrecSaltiness         *float32          `json:"edhrecSaltiness,omitempty"`
	FaceConvertedManaCost   *float64          `json:"faceConvertedManaCost,omitempty"`
	FaceManaValue           *float64          `json:"faceManaValue,omitempty"`
	FaceName                *string           `json:"faceName,omitempty"`
	FirstPrinting           *string           `json:"firstPrinting,omitempty"`
	Hand                    *string           `json:"hand,omitempty"`
	HasAlternativeDeckLimit *bool             `json:"hasAlternativeDeckLimit,omitempty"`
	Identifiers             Identifiers       `json:"identifiers"`
	IsFunny                 *bool             `json:"isFunny,omitempty"`
	IsGameChanger           *bool             `json:"isGameChanger,omitempty"`
	IsReserved              *bool             `json:"isReserved,omitempty"`
	Keywords                *[]string         `json:"keywords,omitempty"`
	Layout                  string            `json:"layout"`
	LeadershipSkills        *LeadershipSkills `json:"leadershipSkills,omitempty"`
	Legalities              Legalities        `json:"legalities"`
	Life                    *string           `json:"life,omitempty"`
	Loyalty                 *string           `json:"loyalty,omitempty"`
	ManaCost                *string           `json:"manaCost,omitempty"`
	ManaValue               float64           `json:"manaValue"`
	Name                    string            `json:"name"`
	Power                   *string           `json:"power,omitempty"`
	Printings               *[]string         `json:"printings,omitempty"`
	PurchaseUrls            PurchaseUrls      `json:"purchaseUrls"`
	RelatedCards            *RelatedCards     `json:"relatedCards,omitempty"`
	Rulings                 *[]Rulings        `json:"rulings,omitempty"`
	Side                    *string           `json:"side,omitempty"`
	Subsets                 *[]string         `json:"subsets,omitempty"`
	Subtypes                []string          `json:"subtypes"`
	Supertypes              []string          `json:"supertypes"`
	Text                    *string           `json:"text,omitempty"`
	Toughness               *string           `json:"toughness,omitempty"`
	Type                    string            `json:"type"`
	Types                   []string          `json:"types"`
}

type CardDeck struct {
	Artist                  *string           `json:"artist,omitempty"`
	ArtistIds               []string          `json:"artistIds,omitempty"`
	AsciiName               *string           `json:"asciiName,omitempty"`
	AttractionLights        []int             `json:"attractionLights,omitempty"`
	Availability            []string          `json:"availability"`
	BoosterTypes            []string          `json:"boosterTypes,omitempty"`
	BorderColor             *string           `json:"borderColor,omitempty"`
	CardParts               []string          `json:"cardParts,omitempty"`
	ColorIdentity           []string          `json:"colorIdentity"`
	ColorIndicator          []string          `json:"colorIndicator,omitempty"`
	Colors                  []string          `json:"colors"`
	ConvertedManaCost       int               `json:"convertedManaCost"`
	Count                   int               `json:"count"`
	Defense                 *string           `json:"defense,omitempty"`
	DuelDeck                *string           `json:"duelDeck,omitempty"`
	EdhrecRank              *int              `json:"edhrecRank,omitempty"`
	EdhrecSaltiness         *float32          `json:"edhrecSaltiness,omitempty"`
	FaceConvertedManaCost   *int              `json:"faceConvertedManaCost,omitempty"`
	FaceFlavorName          *string           `json:"faceFlavorName,omitempty"`
	FaceManaValue           *int              `json:"faceManaValue,omitempty"`
	FaceName                *string           `json:"faceName,omitempty"`
	Finishes                []string          `json:"finishes,omitempty"`
	FlavorName              *string           `json:"flavorName,omitempty"`
	FlavorText              *string           `json:"flavorText,omitempty"`
	ForeignData             []ForeignData     `json:"foreignData,omitempty"`
	FrameEffects            []string          `json:"frameEffects,omitempty"`
	FrameVersion            string            `json:"frameVersion"`
	Hand                    *string           `json:"hand,omitempty"`
	HasAlternativeDeckLimit *bool             `json:"hasAlternativeDeckLimit,omitempty"`
	HasContentWarning       *bool             `json:"hasContentWarning,omitempty"`
	Identifiers             Identifiers       `json:"identifiers"`
	IsAlternative           *bool             `json:"isAlternative,omitempty"`
	IsFoil                  bool              `json:"isFoil"`
	IsFullArt               *bool             `json:"isFullArt,omitempty"`
	IsFunny                 *bool             `json:"isFunny,omitempty"`
	IsGameChanger           *bool             `json:"isGameChanger,omitempty"`
	IsOnlineOnly            *bool             `json:"isOnlineOnly,omitempty"`
	IsOversized             *bool             `json:"isOversized,omitempty"`
	IsPromo                 *bool             `json:"isPromo,omitempty"`
	IsRebalanced            *bool             `json:"isRebalanced,omitempty"`
	IsReprint               *bool             `json:"isReprint,omitempty"`
	IsReserved              *bool             `json:"isReserved,omitempty"`
	IsStorySpotlight        *bool             `json:"isStorySpotlight,omitempty"`
	IsTextless              *bool             `json:"isTextless,omitempty"`
	IsTimeshifted           *bool             `json:"isTimeshifted,omitempty"`
	Keywords                []string          `json:"keywords,omitempty"`
	Language                string            `json:"language"`
	Layout                  string            `json:"layout"`
	LeadershipSkills        *LeadershipSkills `json:"leadershipSkills,omitempty"`
	Legalities              Legalities        `json:"legalities"`
	Life                    *string           `json:"life,omitempty"`
	Loyalty                 *string           `json:"loyalty,omitempty"`
	ManaCost                *string           `json:"manaCost,omitempty"`
	ManaValue               float64           `json:"manaValue"`
	Name                    string            `json:"name"`
	Number                  string            `json:"number"`
	OriginalPrintings       []string          `json:"originalPrintings,omitempty"`
	OriginalReleaseDate     *string           `json:"originalReleaseDate,omitempty"`
	OriginalText            *string           `json:"originalText,omitempty"`
	OriginalType            *string           `json:"originalType,omitempty"`
	OtherFaceIds            []string          `json:"otherFaceIds,omitempty"`
	Power                   *string           `json:"power,omitempty"`
	Printings               []string          `json:"printings,omitempty"`
	PromoTypes              []string          `json:"promoTypes,omitempty"`
	PurchaseUrls            PurchaseUrls      `json:"purchaseUrls"`
	Rarity                  string            `json:"rarity"`
	RebalancedPrintings     []string          `json:"rebalancedPrintings,omitempty"`
	RelatedCards            *RelatedCards     `json:"relatedCards"`
	Rulings                 []Rulings         `json:"rulings,omitempty"`
	SecurityStamp           *string           `json:"securityStamp,omitempty"`
	SetCode                 util.SetCode      `json:"setCode"`
	Side                    *string           `json:"side,omitempty"`
	Signature               *string           `json:"signature,omitempty"`
	SkuIds                  SkuIds            `json:"skuIds"`
	SourceProducts          *SourceProducts   `json:"sourceProducts,omitempty"`
	Subsets                 []string          `json:"subsets,omitempty"`
	Subtypes                []string          `json:"subtypes"`
	Supertypes              []string          `json:"supertypes"`
	Text                    *string           `json:"text,omitempty"`
	Toughness               *string           `json:"toughness,omitempty"`
	Type                    string            `json:"type"`
	Types                   []string          `json:"types"`
	Uuid                    uuid.UUID         `json:"uuid"`
	Variations              []string          `json:"variations,omitempty"`
	Watermark               *string           `json:"watermark,omitempty"`
}

type CardSet struct {
	Artist                  *string           `json:"artist,omitempty"`
	ArtistIds               []string          `json:"artistIds,omitempty"`
	AsciiName               *string           `json:"asciiName,omitempty"`
	AttractionLights        []int             `json:"attractionLights,omitempty"`
	Availability            []string          `json:"availability"`
	BoosterTypes            []string          `json:"boosterTypes,omitempty"`
	BorderColor             string            `json:"borderColor"`
	CardParts               []string          `json:"cardParts,omitempty"`
	ColorIdentity           []string          `json:"colorIdentity"`
	ColorIndicator          []string          `json:"colorIndicator,omitempty"`
	Colors                  []string          `json:"colors"`
	ConvertedManaCost       float64           `json:"convertedManaCost"`
	Defense                 *string           `json:"defense,omitempty"`
	DuelDeck                *string           `json:"duelDeck,omitempty"`
	EdhrecRank              *int              `json:"edhrecRank,omitempty"`
	EdhrecSaltiness         *float32          `json:"edhrecSaltiness,omitempty"`
	FaceConvertedManaCost   *float64          `json:"faceConvertedManaCost,omitempty"`
	FaceFlavorName          *string           `json:"faceFlavorName,omitempty"`
	FaceManaValue           *float64          `json:"faceManaValue,omitempty"`
	FaceName                *string           `json:"faceName,omitempty"`
	Finishes                []string          `json:"finishes"`
	FlavorName              *string           `json:"flavorName,omitempty"`
	FlavorText              *string           `json:"flavorText,omitempty"`
	ForeignData             []ForeignData     `json:"foreignData,omitempty"`
	FrameEffects            []string          `json:"frameEffects,omitempty"`
	FrameVersion            string            `json:"frameVersion"`
	Hand                    *string           `json:"hand,omitempty"`
	HasAlternativeDeckLimit *bool             `json:"hasAlternativeDeckLimit,omitempty"`
	HasContentWarning       *bool             `json:"hasContentWarning,omitempty"`
	Identifiers             Identifiers       `json:"identifiers"`
	IsAlternative           *bool             `json:"isAlternative,omitempty"`
	IsFullArt               *bool             `json:"isFullArt,omitempty"`
	IsFunny                 *bool             `json:"isFunny,omitempty"`
	IsGameChanger           *bool             `json:"isGameChanger,omitempty"`
	IsOnlineOnly            *bool             `json:"isOnlineOnly,omitempty"`
	IsOversized             *bool             `json:"isOversized,omitempty"`
	IsPromo                 *bool             `json:"isPromo,omitempty"`
	IsRebalanced            *bool             `json:"isRebalanced,omitempty"`
	IsReprint               *bool             `json:"isReprint,omitempty"`
	IsReserved              *bool             `json:"isReserved,omitempty"`
	IsStorySpotlight        *bool             `json:"isStorySpotlight,omitempty"`
	IsTextless              *bool             `json:"isTextless,omitempty"`
	IsTimeshifted           *bool             `json:"isTimeshifted,omitempty"`
	Keywords                []string          `json:"keywords,omitempty"`
	Language                string            `json:"language"`
	Layout                  string            `json:"layout"`
	LeadershipSkills        *LeadershipSkills `json:"leadershipSkills,omitempty"`
	Legalities              Legalities        `json:"legalities"`
	Life                    *string           `json:"life,omitempty"`
	Loyalty                 *string           `json:"loyalty,omitempty"`
	ManaCost                *string           `json:"manaCost,omitempty"`
	ManaValue               float64           `json:"manaValue"`
	Name                    string            `json:"name"`
	Number                  string            `json:"number"`
	OriginalPrintings       []string          `json:"originalPrintings,omitempty"`
	OriginalReleaseDate     *string           `json:"originalReleaseDate,omitempty"`
	OriginalText            *string           `json:"originalText,omitempty"`
	OriginalType            *string           `json:"originalType,omitempty"`
	OtherFaceIds            []string          `json:"otherFaceIds,omitempty"`
	Power                   *string           `json:"power,omitempty"`
	Printings               []string          `json:"printings,omitempty"`
	PromoTypes              []string          `json:"promoTypes,omitempty"`
	PurchaseUrls            PurchaseUrls      `json:"purchaseUrls"`
	Rarity                  string            `json:"rarity"`
	RebalancedPrintings     []string          `json:"rebalancedPrintings,omitempty"`
	RelatedCards            *RelatedCards     `json:"relatedCards"`
	Rulings                 []Rulings         `json:"rulings,omitempty"`
	SecurityStamp           *string           `json:"securityStamp,omitempty"`
	SetCode                 util.SetCode      `json:"setCode"`
	Side                    *string           `json:"side,omitempty"`
	Signature               *string           `json:"signature,omitempty"`
	SkuIds                  SkuIds            `json:"skuIds"`
	SourceProducts          *SourceProducts   `json:"sourceProducts,omitempty"`
	Subsets                 []string          `json:"subsets,omitempty"`
	Subtypes                []string          `json:"subtypes"`
	Supertypes              []string          `json:"supertypes"`
	Text                    *string           `json:"text,omitempty"`
	Toughness               *string           `json:"toughness,omitempty"`
	Type                    string            `json:"type"`
	Types                   []string          `json:"types"`
	Uuid                    uuid.UUID         `json:"uuid"`
	Variations              []string          `json:"variations,omitempty"`
	Watermark               *string           `json:"watermark,omitempty"`
}

type CardSetDeck struct {
	Count  int       `json:"count"`
	IsFoil *bool     `json:"isFoil,omitempty"`
	Uuid   uuid.UUID `json:"uuid"`
}

type CardToken struct {
	Artist           *string         `json:"artist,omitempty"`
	ArtistIds        []string        `json:"artistIds,omitempty"`
	AsciiName        *string         `json:"asciiName,omitempty"`
	AttractionLights []int           `json:"attractionLights,omitempty"`
	Availability     []string        `json:"availability"`
	BoosterTypes     []string        `json:"boosterTypes,omitempty"`
	BorderColor      string          `json:"borderColor"`
	CardParts        []string        `json:"cardParts,omitempty"`
	ColorIdentity    []string        `json:"colorIdentity"`
	ColorIndicator   []string        `json:"colorIndicator,omitempty"`
	Colors           []string        `json:"colors"`
	EdhrecSaltiness  *float32        `json:"edhrecSaltiness,omitempty"`
	FaceFlavorName   *string         `json:"faceFlavorName,omitempty"`
	FaceName         *string         `json:"faceName,omitempty"`
	Finishes         []string        `json:"finishes"`
	FlavorName       *string         `json:"flavorName,omitempty"`
	FlavorText       *string         `json:"flavorText,omitempty"`
	FrameEffects     []string        `json:"frameEffects,omitempty"`
	FrameVersion     string          `json:"frameVersion"`
	Identifiers      Identifiers     `json:"identifiers"`
	IsFullArt        *bool           `json:"isFullArt,omitempty"`
	IsFunny          *bool           `json:"isFunny,omitempty"`
	IsOnlineOnly     *bool           `json:"isOnlineOnly,omitempty"`
	IsOversized      *bool           `json:"isOversized,omitempty"`
	IsPromo          *bool           `json:"isPromo,omitempty"`
	IsReprint        *bool           `json:"isReprint,omitempty"`
	IsTextless       *bool           `json:"isTextless,omitempty"`
	Keywords         []string        `json:"keywords,omitempty"`
	Language         string          `json:"language"`
	Layout           string          `json:"layout"`
	Loyalty          *string         `json:"loyalty,omitempty"`
	ManaCost         *string         `json:"manaCost,omitempty"`
	Name             string          `json:"name"`
	Number           string          `json:"number"`
	Orientation      *string         `json:"orientation,omitempty"`
	OriginalText     *string         `json:"originalText,omitempty"`
	OriginalType     *string         `json:"originalType,omitempty"`
	OtherFaceIds     []string        `json:"otherFaceIds,omitempty"`
	Power            *string         `json:"power,omitempty"`
	PromoTypes       []string        `json:"promoTypes,omitempty"`
	RelatedCards     *RelatedCards   `json:"relatedCards,omitempty"`
	SecurityStamp    *string         `json:"securityStamp,omitempty"`
	SetCode          util.SetCode    `json:"setCode"`
	Side             *string         `json:"side,omitempty"`
	Signature        *string         `json:"signature,omitempty"`
	SkuIds           SkuIds          `json:"skuIds"`
	SourceProducts   *SourceProducts `json:"sourceProducts,omitempty"`
	Subsets          []string        `json:"subsets,omitempty"`
	Subtypes         []string        `json:"subtypes"`
	Supertypes       []string        `json:"supertypes"`
	Text             *string         `json:"text,omitempty"`
	Toughness        *string         `json:"toughness,omitempty"`
	Type             string          `json:"type"`
	Types            []string        `json:"types"`
	Uuid             uuid.UUID       `json:"uuid"`
	Watermark        *string         `json:"watermark,omitempty"`
}
